name: pocsdeblend
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - numba
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy>=1.4.0
  - pandas
  - cupy
  - cuda-version=11.4
  - numba
  - icc_rt
  - matplotlib
  - tqdm
  - ipython
  - jupyter
  - pip
    - celluloid
    - git+https://github.com/pylops/pylops@dev
    - git+https://github.com/pylops/pyproximal@dev